### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by YuhaoYeSteve** [yu4u/convnet-drawer#4]
Hi, I follow every step of the instruction, however, does not work, anyone can help me, thank you!

Traceback (most recent call last):
  File "D:/lyceum/plot_CNN_architecture/CNN_archi.py", line 23, in <module>
    save_model_to_pptx(model, "1.pptx")
  File "D:\lyceum\plot_CNN_architecture\pptx_util.py", line 63, in save_model_to_pptx
    presentation.add_line(obj.x1, obj.y1, obj.x2, obj.y2, obj.color, obj.width, obj.dasharray)
  File "D:\lyceum\plot_CNN_architecture\pptx_util.py", line 29, in add_line
    connector.ln = connector.get_or_add_ln()
AttributeError: can't set attribute

**Comment by yu4u** [comment]
Thank you for your report.
This problem occurred for python-pptx >= 0.6.12.
I fixed the issue, so please update this project and try again.

**Comment by YuhaoYeSteve** [comment]
It is working now. Thanks a lot!
